# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty strings
google-ID: 'G-33LWZVJY9E'

menu:
- {name: 'Tentang Hanif',   url: 'tentang-hanif.html'}
- {name: 'Kontak', url: 'kontak-hanif.html'}
- {name: 'Karya', url: 'karya-hanif.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/gondolasoy'}
- {icon: 'twitter',    link: 'https://twitter.com/gondolasoy'}
- {icon: 'envelope',   link: 'mailto:hanifamin16@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'konten baru'
  previous_page: 'konten lama'

sharing_button_prompt: 'boleh di-share'

related_posts: 'tulisan terkait:'

post_date_prefix: 'Dipublikasi pada'

